version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 8000:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  # phpmyadminの設定が書きに記載します。
  phpmyadmin:
    #コンテナ名を決めています。
    container_name: phpmyadmin
    #DockerHubからphpmyadminのイメージを引っ張ってくる設定です。
    image: phpmyadmin/phpmyadmin
    #phpmyadminの環境変数の設定です。MySQLの設定を参照して記載してください。PMA_HOSTSにはservicesのdbを指定しています。
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 3000:80
  
volumes:
  db-store: